<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60d72f2177150',
	'title' => 'Image parallax',
	'fields' => array(
		array(
			'key' => 'field_60d72f217dbac',
			'label' => 'Content',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60d72f217dbed',
			'label' => 'Image',
			'name' => 'image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_60d72f217dc2e',
			'label' => 'Configuration',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'placement' => 'top',
			'endpoint' => 0,
			'no_preference' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_60d72f217dc6e',
			'label' => 'Advanced mode',
			'name' => 'advanced_mode',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_60d72f217dcaf',
			'label' => 'Container width',
			'name' => 'container_width',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'acfe_field_group_condition' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_60d72f2189b7e',
					'label' => 'Mobile',
					'name' => 'default',
					'type' => 'select',
					'instructions' => 'Below 640px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189bc1',
					'label' => 'Tablet',
					'name' => 'sm',
					'type' => 'select',
					'instructions' => 'Between 640px and 1024px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189c01',
					'label' => 'Desktop',
					'name' => 'lg',
					'type' => 'select',
					'instructions' => 'Above 1024px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189c41',
					'label' => 'Mobile',
					'name' => 'default_advanced',
					'type' => 'select',
					'instructions' => 'Below 640px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '16',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189c7f',
					'label' => 'Tablet (portrait)',
					'name' => 'sm_advanced',
					'type' => 'select',
					'instructions' => 'Between 640px and 768px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '16',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189cbf',
					'label' => 'Tablet (landscape)',
					'name' => 'md_advanced',
					'type' => 'select',
					'instructions' => 'Between 768px and 1024px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '16',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189cfe',
					'label' => 'Small desktop',
					'name' => 'lg_advanced',
					'type' => 'select',
					'instructions' => 'Between 1024px and 1280px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '16',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189d3d',
					'label' => 'Desktop',
					'name' => 'xl_advanced',
					'type' => 'select',
					'instructions' => 'Between 1280px and 1536px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '16',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_60d72f2189d7c',
					'label' => 'Large desktop',
					'name' => '2xl_advanced',
					'type' => 'select',
					'instructions' => 'Above 1536px',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60d72f217dc6e',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '16',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'choices' => array(
						'w-1/2' => 'Small',
						'w-8/12' => 'Medium',
						'w-10/12' => 'Large',
						'w-full' => 'Full width',
					),
					'default_value' => 'w-full',
					'allow_null' => 0,
					'multiple' => 0,
					'max' => '',
					'ui' => 0,
					'return_format' => 'value',
					'acfe_field_group_condition' => 0,
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_60d72f217dcee',
			'label' => 'Image height',
			'name' => 'img_height',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 300,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 1,
			'max' => '',
			'step' => 1,
			'acfe_field_group_condition' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'_pip_thumbnail' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'_pip_is_layout' => 1,
	'_pip_layout_slug' => 'image-contained-parallax-seabass',
	'_pip_render_layout' => 'image-contained-parallax-seabass.php',
	'_pip_render_style' => 'image-contained-parallax-seabass.css',
	'_pip_render_script' => 'image-contained-parallax-seabass.js',
	'field_add_config_file' => 0,
	'field_add_configuration' => 0,
	'pip_layout_var' => array(
		'row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-601aa114846a4' => array(
			'pip_layout_var_key' => 'wrapper-image',
			'pip_layout_var_value' => '',
		),
		'row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-601aa114846a5' => array(
			'pip_layout_var_key' => 'image',
			'pip_layout_var_value' => 'w-full object-cover object-center',
		),
		'row-row-row-row-row-row-row-row-row-row-row-row-60d731654ce87' => array(
			'pip_layout_var_key' => 'background-parallax',
			'pip_layout_var_value' => 'bg-fixed bg-center bg-no-repeat bg-cover h-96 min-w-full',
		),
	),
	'pip_layout_vars_lock' => 0,
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'layout_categories' => array(
		'image' => 'Image',
	),
	'layout_collections' => array(
		'seabass' => 'seabass',
	),
	'modified' => 1625059652,
));

endif;