<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60ba159e13c0a',
	'title' => 'Progress bar',
	'fields' => array(
		array(
			'key' => 'field_60ba8705214c1',
			'label' => 'Configuration',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60ba814f0f0d7',
			'label' => 'Bar height',
			'name' => 'bar_height',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'choices' => array(
				'4px' => '4px',
				'8px' => '8px',
				'12px' => '12px',
				'16px' => '16px',
				'20px' => '20px',
				'24px' => '24px',
				'28px' => '28px',
				'32px' => '32px',
			),
			'default_value' => '8px',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_60ba821654cd5',
			'label' => 'empty bar color',
			'name' => 'empty_bar_color',
			'type' => 'pip_font_color',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'field_type' => 'select',
			'multiple' => 0,
			'ui' => 0,
			'pip_default_value' => 'gray-gris-300',
			'class_output' => 'background',
			'show_add_to_editor' => 1,
			'choices' => array(
			),
			'placeholder' => '',
			'return_format' => 'value',
			'allow_null' => true,
			'other_choice' => 0,
			'allow_custom' => 0,
			'ajax' => false,
		),
		array(
			'key' => 'field_60ba825b54cd6',
			'label' => 'progress bar color',
			'name' => 'progress_bar_color',
			'type' => 'pip_font_color',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'field_type' => 'select',
			'multiple' => 0,
			'ui' => 0,
			'pip_default_value' => 'primary-primaire-300',
			'class_output' => 'background',
			'show_add_to_editor' => 1,
			'choices' => array(
			),
			'placeholder' => '',
			'return_format' => 'value',
			'allow_null' => true,
			'other_choice' => 0,
			'allow_custom' => 0,
			'ajax' => false,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'_pip_thumbnail' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'_pip_is_layout' => 1,
	'_pip_layout_slug' => 'progress-bar',
	'_pip_render_layout' => 'progress-bar.php',
	'_pip_render_style' => 'progress-bar.css',
	'_pip_render_script' => 'progress-bar.js',
	'field_add_config_file' => 0,
	'field_add_configuration' => 0,
	'pip_layout_var' => array(
		'row-row-row-row-row-row-row-row-row-row-row-row-60ba3140d89a4' => array(
			'pip_layout_var_key' => 'content-wrapper',
			'pip_layout_var_value' => 'sticky top-0',
		),
		'row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-60ba1f8c4bb84' => array(
			'pip_layout_var_key' => 'bg_color_contain',
			'pip_layout_var_value' => 'w-full sticky top-0',
		),
		'row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-row-60ba28be4bb85' => array(
			'pip_layout_var_key' => 'bg_color_progress',
			'pip_layout_var_value' => 'w-0',
		),
	),
	'pip_layout_vars_lock' => 0,
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'layout_collections' => array(
		'seabass' => 'seabass',
	),
	'modified' => 1622879893,
));

endif;