<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_60d304fb45ee3',
	'title' => 'Menu',
	'fields' => array(
		array(
			'key' => 'field_60d304fb4cada',
			'label' => 'Background color',
			'name' => 'section_bg_color',
			'type' => 'pip_font_color',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'field_type' => 'select',
			'multiple' => 0,
			'ui' => 0,
			'pip_default_value' => '',
			'class_output' => 'background',
			'show_add_to_editor' => 1,
			'choices' => array(
			),
			'placeholder' => '',
			'return_format' => 'value',
			'allow_null' => true,
			'other_choice' => 0,
			'allow_custom' => 0,
			'ajax' => false,
		),
		array(
			'key' => 'field_60d304fb4cb1e',
			'label' => 'Logo (transparent background)',
			'name' => 'logo_transparent',
			'type' => 'image',
			'instructions' => 'Leave empty to use logo defined in <i>Appearance</i> > <i>Customize</i>.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_60d304fb4cb5e',
			'label' => 'Logo (colored background)',
			'name' => 'logo_background',
			'type' => 'image',
			'instructions' => 'Leave empty to use logo defined in <i>Appearance</i> > <i>Customize</i>.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_60d4459a3e134',
			'label' => 'Sticky',
			'name' => 'sticky',
			'type' => 'select',
			'instructions' => 'Select if you want sticky menu',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'relative' => 'relative',
				'fixed w-full z-10' => 'fixed w-full z-10',
			),
			'default_value' => 'relative',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'pip-pattern',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'_pip_thumbnail' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'_pip_is_layout' => 1,
	'_pip_layout_slug' => 'menu-contained-seabass',
	'_pip_render_layout' => 'menu-contained-seabass.php',
	'_pip_render_style' => 'menu-contained-seabass.css',
	'_pip_render_script' => 'menu-contained-seabass.js',
	'field_add_config_file' => 1,
	'_pip_config_file' => 'configuration.php',
	'field_add_configuration' => 0,
	'pip_layout_var' => array(
		'row-row-60d4488552d47' => array(
			'pip_layout_var_key' => 'wrapper-main-transparent',
			'pip_layout_var_value' => 'h-20 ',
		),
		'row-row-60d4488452d46' => array(
			'pip_layout_var_key' => 'scroll-wrapper-main-transparent',
			'pip_layout_var_value' => 'h-20',
		),
		'row-row-60d4488452d45' => array(
			'pip_layout_var_key' => 'wrapper-main-color',
			'pip_layout_var_value' => 'h-20',
		),
		'row-row-60d4488452d44' => array(
			'pip_layout_var_key' => 'scroll-wrapper-main-color',
			'pip_layout_var_value' => 'h-20',
		),
		'row-row-60d4488452d43' => array(
			'pip_layout_var_key' => 'inner-wrapper-main',
			'pip_layout_var_value' => 'flex items-center justify-between lg:justify-start h-full',
		),
		'row-row-60d4488452d42' => array(
			'pip_layout_var_key' => 'wrapper-logo',
			'pip_layout_var_value' => 'z-10',
		),
		'row-row-60d4488452d41' => array(
			'pip_layout_var_key' => 'wrapper-menu-items',
			'pip_layout_var_value' => 'hidden lg:flex w-full h-auto lg:h-full items-center justify-end absolute lg:static top-20 left-0 bg-white lg:bg-transparent z-10 p-4',
		),
		'row-row-60d4488352d40' => array(
			'pip_layout_var_key' => 'scroll-after-nb-pixels',
			'pip_layout_var_value' => '',
		),
		'row-row-60d4488352d3f' => array(
			'pip_layout_var_key' => 'logo',
			'pip_layout_var_value' => 'h-16 w-16 object-center object-cover',
		),
		'row-row-60d4488352d3e' => array(
			'pip_layout_var_key' => 'menu-classes-transparent',
			'pip_layout_var_value' => 'lg:flex items-center h-full p-4 lg:p-0 lg:text-black',
		),
		'row-row-60d4488352d3d' => array(
			'pip_layout_var_key' => 'menu-classes-color',
			'pip_layout_var_value' => 'lg:flex items-center h-full p-4 lg:p-0',
		),
		'row-row-60d4488352d3c' => array(
			'pip_layout_var_key' => 'wrapper-burger-button',
			'pip_layout_var_value' => 'block lg:hidden z-10',
		),
		'row-row-60d4488352d3b' => array(
			'pip_layout_var_key' => 'burger-button-transparent',
			'pip_layout_var_value' => 'flex items-center px-3 py-2 rounded text-blue-800 focus:text-primary focus:outline-none hover:text-blue-500',
		),
		'row-row-60d4488352d3a' => array(
			'pip_layout_var_key' => 'burger-button-color',
			'pip_layout_var_value' => 'flex items-center px-3 py-2 rounded text-black focus:text-blue-800 focus:outline-none hover:text-blue-500',
		),
		'row-row-60d4488152d39' => array(
			'pip_layout_var_key' => 'burger-button-close',
			'pip_layout_var_value' => 'fill-current h-6 w-6',
		),
		'row-row-60d4487152d38' => array(
			'pip_layout_var_key' => 'burger-button-open',
			'pip_layout_var_value' => 'h-6 w-6 fill-current hidden',
		),
	),
	'pip_layout_vars_lock' => 0,
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'layout_categories' => array(
		'menu' => 'Menu',
	),
	'layout_collections' => array(
		'seabass' => 'seabass',
	),
));

endif;